[package]
name = "euclidean"
version = "0.1.0"
entrypoint = "src/euclidean.typ"
authors = ["nabilnnw"]
license = "MIT"
description = "a CeTZ wrapper focusing on 2D math geometry olympiad"
categories = ["utility"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png" # Not yet
